### PR TITLE
New Score graphics

### PR DESCRIPTION
**Pull request by knowuh**
Small changes to use the new score scale graphics.

(Please review these PR's in order, because they are based off each other)

### CODE REVIEW

**Comment by pjanik** [comment]
Looks good, but a few questions re webpack config:
- Do we need `contentBase` option? I don't really understand it.
- `require('path')` seems to be unused.
- I guess we could configure CopyPlugin to copy the whole `/public` dir, so we don't need to list all the files (or file types) there.

Very small items, but I would keep this config small / clean.

**Comment by knowuh** [comment]
Good catch on `require('path')` and I agree,  we should just copy everything from `public`. 

The contentBase will serve everything from `public` as static content when running  `webpack-dev-server`.  It doesn't seem like CopyPlugin helps us with that.

**Comment by pjanik** [comment]
CopyPlugin copies everything from `/public` to `/dist`. And webpack-dev-server serves everything which ends up in `/dist` during build process (but I guess it keeps it in memory). The only issue I have is that I need to restart webpack-dev-server when I add or update resources in `/public` dir. So, if this helps with that, that's great. If not, I guess we probably don't need it.

**Comment by pjanik** [comment]
@knowuh, I've just seen your question on Slack about CopyPlugin + webpack-dev-server. I've realized I never copy images using CopyPlugin. I've been always using FileLoader or ImageLoader to require image in JS file (webpack returns its auto-generated path), e.g.:
https://github.com/concord-consortium/portal-report/blob/3d9948c184bc5b860a8254e3b5e07e36414119e3/js/containers/app.js#L12
Benefits:
- we don't deploy unused resources and probably it's easier to cleanup unused ones
- when webpack copies image to /dist, it generates nice name based on SHA, so it can solve caching issues
- ImageLoader can inline small images (it's configurable)

**Comment by knowuh** [comment]
What I am wondering about ImageLoader:  If we are dynamically generating the image name based on attributes eg: `"./images/#{score}-#{max_score}pt-scale.png"`  -- how can we resolve this? 

We could `require` all the images but since they may be converted to base64 inline images, we would have to use a 10-way switch statement to match up each score/max-score combination to the required image resource by variable name.  Seems like too much?

**Comment by knowuh** [comment]
@pjanik I am going to merge this, because I think the `webpack.config.js` is even smaller / cleaner now.

**Comment by pjanik** [comment]
> We could require all the images but since they may be converted to base64 inline images, we would have to use a 10-way switch statement to match up each score/max-score combination to the required image resource by variable name. Seems like too much?

Or use some hash / map, simple module that handles that. I guess I would be prefer it since we use webpack, but it's not important.

> @pjanik I am going to merge this

Sorry, I left my tab open and forgot to click "Comment". Looks good, thanks! 👍

**Pull request merged**
