### PR TITLE
Add group members to submission info

### PR DESCRIPTION
**Pull request by pjanik**
Each submission is attributed to all of the members of the group that made the submission.
Also, submissions are sorted and the most recent one is displayed at the top (I remember that someone requested thad during one of the demo meetings, right?).

### CODE REVIEW

**Comment by pjanik** [comment]
This PR includes one more change: when two students have the same first and last names, their username is appended to their full name. E.g.:
`John Smith (jsmith1)`
`John Smith (jsmith2)`

Username is appended to `student_name` property during initial data processing, so components don't need to handle that separately.

**Comment by pjanik** [comment]
I'm working on that more, so groups are also displayed on the question details page (but had to work on the page itself first).

**Comment by pjanik** [comment]
Okay, this PR ready now. Now, it affects both student and question details pages.
It also includes some refactoring related to components shared between these pages and data processing. Data helpers are moved to a separate file, I also tried to come up with better names for various state properties, so they're more consistent.

**Comment by knowuh** [comment]
Looks good :+1:

**Pull request merged**
